#!name=Blued - Block ads
#!desc=Blued block ads on startup.

[MITM]
hostname = %APPEND% argo.blued.cn

[Script]
Blued = type=http-response,pattern=https:\/\/argo\.blued\.cn\/blued\/splash.*,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js
Blued = type=http-response,pattern=https:\/\/argo\.blued\.cn\/users\/.*page.*,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js