#!name=Blued - Unlock User Profile
#!desc=Blued Unlock User Profile.

[Script]
http-response ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-user-profile-permission.js,requires-body=true

http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-user-profile-permission.js,requires-body=true