#!name=Blued - Filter list
#!desc=Blued filter list by note.

[MITM]
tcp-connection = true
hostname = %APPEND% argo.blued.cn:0, 106.75.55.121, 106.75.33.126, 106.75.70.21

[Script]
Blued = type=http-response,pattern=^https:\/\/argo\.blued\.cn\/users\?filters.*$,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js

Blued = type=http-response,pattern=^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\?filters.*$,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js