#!name=Blued burn chatfiles
#!desc=Perform MitM on Blued burn chatfiles.

[Replica]
keyword-filter-type = pattern
keyword-filter = %APPEND% *burn-chatfiles*

[MITM]
hostname = %APPEND% *bldimg*

[Script]
http-request ^https://burn-chatfiles.bldimg.com/* script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-start.js
http-response ^https://burn-chatfiles.bldimg.com/* script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-stop.js