#!name=Blued - Auto note
#!desc=Blued automatically make note.

[MITM]
hostname = %APPEND% argo.blued.cn, 106.75.55.121, 106.75.33.126, 106.75.70.21

[Script]
http-request ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\/more\/.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-id.js
http-request ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-headers.js
http-response ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js,requires-body=true

http-request ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\/more\/.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-id.js
http-request ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-headers.js
http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js,requires-body=true