#!name=Blued - Filter list
#!desc=Blued filter list by note.

[MITM]
hostname = %APPEND% *.blued.cn, -*im.blued.cn

[Script]
http-response ^blued-set-filter$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-set-filter.js,requires-body=true

http-response ^https:\/\/argo\.blued\.cn\/users\?.*filters.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js,requires-body=true

http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\?.*filters.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js,requires-body=true