#!name=Blued - Auto note
#!desc=Blued automatically make note.

[MITM]
hostname = %APPEND% *.blued.cn

[Script]
http-request ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\/more\/.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-id.js
http-response ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js,requires-body=true
http-request ^https:\/\/argo\.blued\.cn\/ticktocks\/users\/[0-9]+\/timeline\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-headers.js
http-request ^https:\/\/argo\.blued\.cn\/ticktocks\/users\/[0-9]+\/photowall\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js,requires-body=true