#!name=Blued - Auto note
#!desc=Blued automatically make note.

[MITM]
hostname = %APPEND% *blued.cn

[Script]
http-response ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-user-profile-permission.js,requires-body=true

http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-user-profile-permission.js,requires-body=true