#!name=Blued - Block ads
#!desc=Blued block ads on startup.

[MITM]
hostname = %APPEND% *.blued.cn, 116.211.78.11, 23.76.216.42

[Script]
http-response ^https:\/\/argo\.blued\.cn\/blued\/splash.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js,requires-body=true
http-response ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\/(visitors|visited)\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js,requires-body=true

http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/blued\/splash.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js,requires-body=true
http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\/(visitors|visited)\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js,requires-body=true