#!name=Blued burn chatfiles and block Ads
#!desc=Perform MitM on Blued burn chatfiles and block Ads.

[Replica]
keyword-filter-type = pattern
keyword-filter = %APPEND% *burn-chatfiles*

[MITM]
hostname = %APPEND% *bldimg*, argo.blued.cn

[Script]
Blued = type=http-request,pattern=https:\/\/burn-chatfiles\.bldimg\.com\/.*,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-start.js
Blued = type=http-response,pattern=https:\/\/burn-chatfiles\.bldimg\.com\/.*,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-stop.js
Blued = type=http-response,pattern=https:\/\/argo\.blued\.cn\/blued\/splash.*,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js
Blued = type=http-response,pattern=https:\/\/argo\.blued\.cn\/blued\/users\/.*page.*,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-block-ads.js