#!name=Blued - Filter list
#!desc=Blued filter list by note.

[MITM]
hostname = %APPEND% argo.blued.cn, 106.75.55.121, 106.75.33.126, 106.75.70.21

[Script]
http-response ^https:\/\/argo\.blued\.cn\/users\?filters.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js,requires-body=true

http-response ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\?filters.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-filter-list.js,requires-body=true