#!name=Blued - Burn chatfiles
#!desc=Capture Blued burn chatfiles.

[Replica]
keyword-filter-type = pattern
keyword-filter = %APPEND% *burn-chatfiles*

[MITM]
hostname = %APPEND% *bldimg*

[Script]
// blued-burn-chat-files-cap-start = type=http-request,pattern=https:\/\/burn-chatfiles\.bldimg\.com\/.*,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-start.js
blued-burn-chat-files-cap-stop = type=http-response,pattern=https:\/\/burn-chatfiles\.bldimg\.com\/.*,requires-body=true,script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-burn-chat-files-cap-stop.js