#!name=Blued - Auto note
#!desc=Blued automatically make note.

[MITM]
hostname = %APPEND% *.blued.cn

[Script]
http-request ^https:\/\/argo\.blued\.cn\/users\/[0-9]+\/more\/.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-id.js
http-request ^https:\/\/argo\.blued\.cn\/live\/log$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-headers.js
http-request ^https:\/\/argo\.blued\.cn\/ticktocks\/users\/[0-9]+\/timeline\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js

http-request ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/users\/[0-9]+\/more\/.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-id.js
http-request ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/live\/log$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-get-headers.js
http-request ^https:\/\/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/ticktocks\/users\/[0-9]+\/timeline\?.*$ script-path=https://raw.githubusercontent.com/ninjai/rules/master/surge/surge3/script/blued-auto-note.js