#!name=MitM All Hostnames
#!desc=Perform MitM on all hostnames with port 443, except those to Apple and other common sites which can't be inspected. You still need to configure a CA certificate and enable the main switch of MitM.

[Replica]
use-keyword-filter = false
hide-udp = false

[MITM]
tcp-connection = true
hostname = -*.air-matters.com, -*.apple.com, -*.crashlytics.com, -*.facebook.com, -*grindr.mobi, -*.icloud.com, -*.instagram.com, -*.mzstatic.com, -*.scruffapp.com, -*.tantanapp.com, -*.twitter.com, -*.webank.com, *