#!name=TikTok
#!desc=Remove TikTok's regional restrictions.
#!system=ios

[Rule]
USER-AGENT,tiktok*
DOMAIN-KEYWORD,-tiktokcdn-com
DOMAIN-SUFFIX,byteoversea.com
DOMAIN-SUFFIX,ibytedtos.com
DOMAIN-SUFFIX,ipstatp.com
DOMAIN-SUFFIX,muscdn.com
DOMAIN-SUFFIX,musical.ly
DOMAIN-SUFFIX,tik-tokapi.com
DOMAIN-SUFFIX,tiktok.com
DOMAIN-SUFFIX,tiktokcdn.com
DOMAIN-SUFFIX,tiktokv.com

[URL Rewrite]
(?<=&mcc_mnc=)4 2 307
(?<=\d\/\?\w{7}_\w{4}=)1[6-9]..(?=.?.?&) 18.4 307
(?<=_region=)CN(?=&) US 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$4 302

[MITM]
hostname = %APPEND% *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com